# Basic Python

## 1. Split this string

In [27]:
s = "Hi there Sam!"

In [28]:
string = s.split()
print(string)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [29]:
planet = "Earth"
diameter = 12742

In [30]:
print("The diameter of {p_name} is {dia} kilometers".format(p_name = planet,dia = diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [31]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [32]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [33]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [34]:
import numpy as np
array=np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [36]:
li=[]
for i in range(20,35):
    if(i%2==0):
        li.append(i)
print(li)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [37]:
import random
a=[[0]*3]*3
for i in range(3):
    for j in range(3):
        a[i][j]=random.randint(0,9)
print(a)

[[7, 6, 4], [7, 6, 4], [7, 6, 4]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
concat = np.concatenate((a, b), axis = None)
  
print (concat)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [39]:
import pandas as pd


In [40]:
df = pd.DataFrame(index=['1','2','3'], columns=['1','2'])
df

1    2
1  NaN  NaN
2  NaN  NaN
3  NaN  NaN

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [41]:
import pandas as pd
from datetime import datetime

pd.date_range(start="2023-01-01",end="2023-02-10").to_pydatetime().tolist()

[datetime.datetime(2023, 1, 1, 0, 0),
 datetime.datetime(2023, 1, 2, 0, 0),
 datetime.datetime(2023, 1, 3, 0, 0),
 datetime.datetime(2023, 1, 4, 0, 0),
 datetime.datetime(2023, 1, 5, 0, 0),
 datetime.datetime(2023, 1, 6, 0, 0),
 datetime.datetime(2023, 1, 7, 0, 0),
 datetime.datetime(2023, 1, 8, 0, 0),
 datetime.datetime(2023, 1, 9, 0, 0),
 datetime.datetime(2023, 1, 10, 0, 0),
 datetime.datetime(2023, 1, 11, 0, 0),
 datetime.datetime(2023, 1, 12, 0, 0),
 datetime.datetime(2023, 1, 13, 0, 0),
 datetime.datetime(2023, 1, 14, 0, 0),
 datetime.datetime(2023, 1, 15, 0, 0),
 datetime.datetime(2023, 1, 16, 0, 0),
 datetime.datetime(2023, 1, 17, 0, 0),
 datetime.datetime(2023, 1, 18, 0, 0),
 datetime.datetime(2023, 1, 19, 0, 0),
 datetime.datetime(2023, 1, 20, 0, 0),
 datetime.datetime(2023, 1, 21, 0, 0),
 datetime.datetime(2023, 1, 22, 0, 0),
 datetime.datetime(2023, 1, 23, 0, 0),
 datetime.datetime(2023, 1, 24, 0, 0),
 datetime.datetime(2023, 1, 25, 0, 0),
 datetime.datetime(2023, 1, 26, 0,

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [42]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [43]:
df = pd.DataFrame(lists, index = ['1','2','3'], columns=['1', '2','3'])
df

1    2   3
1  1  aaa  22
2  2  bbb  25
3  3  ccc  24